### ISSUE TITLE
DB Credentials incorrect when within main pod

### ISSUE THREAD

**Issue by huang-jy** [small-hack/pixelfed-chart#56]
After fixing the start up issue, I've now tried to create the test user using the example provided in the docs, but tweaked a bit to represent my local setup:

```
kubectl exec -n pixelfed -it pixelfed-bd8cb75b9-f6jcj -- /bin/bash -c "php artisan user:create --name=myname --username=myusername --email=myname@example.tld --password=password --is_admin=false --confirm_email=true"
Creating a new user...

   Illuminate\Database\QueryException 

  SQLSTATE[08006] [7] connection to server at "postgresql" (10.108.150.21), port 5432 failed: FATAL:  password authentication failed for user "postgres" (Connection: pgsql, SQL: insert into "users" ("username", "name", "email", "password", "is_admin", "email_verified_at", "updated_at", "created_at") values (myusername, myname, myname@example.tld, $2y$10$.nOUNAJHdVaCbMuGfiX3JuyZH/rGOtII3Lfrr6UZDL4hH/xIwKeE6, 0, 2025-01-24 19:00:34, 2025-01-24 19:00:34, 2025-01-24 19:00:34) returning "id")

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕ 
  ➜ 825▕             throw new QueryException(
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

      +19 vendor frames 

  20  app/Console/Commands/UserCreate.php:57
      Illuminate\Database\Eloquent\Model::save()
      +12 vendor frames 

  33  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

command terminated with exit code 1

```

It appears to be able to connect to the database, but not able to authenticate with it.

I suspect this may also be the reason why I see this on the homepage:

![Image](https://github.com/user-attachments/assets/37f6e1ef-8424-46b2-ac6f-3e6d525a2258)

**Comment by jessebot** [comment]
Hmmm, I'm not sure why this is happening.

1. Can you confirm which version of the chart you are using?

2. Can you provide your values.yaml (after anonymizing any sensitive data)?

**Comment by huang-jy** [comment]
I used both my forked repo (after I resynced it) and the one from your repo.

Let me check the values yaml vs the base yaml

**Comment by jessebot** [comment]
Are you completely wiping in between test installs? Also did you clean up any persistent volumes after your installs?

**Comment by huang-jy** [comment]
100%, I explicity go in and delete all pvcs and then the namespace as well when I'm uninstalling.

Also, there seems to be a discrepancy between the values returned when doing 

```
helm inspect values pixelfed-jessebot/pixelfed >pixelfed-values.yaml
```

and the values.yaml in the repo.

For the most part, it's just comments

But these blocks:

https://github.com/small-hack/pixelfed-chart/blob/d5899ba377f9fa83f7d6861ec79fea7fd5c8f36e/charts/pixelfed/values.yaml#L309-L321

https://github.com/small-hack/pixelfed-chart/blob/d5899ba377f9fa83f7d6861ec79fea7fd5c8f36e/charts/pixelfed/values.yaml#L617-L636

Are in the repo values.yaml, but not in the chart values when being extracted by helm inspect

**Comment by huang-jy** [comment]
> I used both my forked repo (after I resynced it) and the one from your repo.
> 
> Let me check the values yaml vs the base yaml

Here's my values.yaml:

```yaml
image:
  registry: ghcr.io
  # -- you can see the source [ghcr.io/mattlqx/docker-pixelfed](https://ghcr.io/mattlqx/docker-pixelfed)
  repository: mattlqx/docker-pixelfed
  # -- This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion
  # (v0.12.4-nginx is currently broken due to migration errors with postgresl,
  # so please either pin a sha tag or use dev-nging as the tag)
  # tag: "7d1d62c8552683225456c2a552ba8ca36afb24b32f706e425310de5bf84aeab1"
  tag: dev-nginx

# This block is for setting up the ingress for more information can be found here:
# https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  # -- enable deploy an Ingress resource - network traffic from outside the cluster
  enabled: true
  # -- ingress class name, e.g. nginx
  className: "nginx"
  # annotations to apply to the Ingress resource
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: pixelfed.mydomain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: pixelfed-tls
      hosts:
        - pixelfed.mydomain.com

postgresql:

  volumePermissions:
    # -- If you get "mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied"
    # error, set these (This often happens on setups like minikube)
    enabled: true

pixelfed:
  # -- timezone for docker container
  timezone: "europe/london"

  # app specific settings
  app:
    # -- change this to the domain of your pixelfed instance
    url: "https://pixelfed.mydomain.com"
    # -- change this to the language code of your pixelfed instance
    locale: "en"
    # -- The domain of your server, without https://
    domain: "pixelfed.mydomain.com"

  # -- Enable open registration for new accounts
  open_registration: false

  # Mail Configuration (Post-Installer)
  mail:
    # -- options: "smtp" (default), "sendmail", "mailgun", "mandrill", "ses"
    # "sparkpost", "log", "array"
    driver: smtp
    # -- mail server hostname
    host: smtp.mailgun.org
    # -- mail server port
    port: 465
    # -- mail server username
    username: "gitlab@mydomain.com"
    # -- mail server password
    password: "REDACTED"
    # -- mail server encryption type
    encryption: "tls"
    # -- address to use for sending emails
    from_address: "pixelfed@mydomain.com"
    # -- name to use for sending emails
    from_name: "Pixelfed"
```

Obviously `mydomain.com` isn't actually my domain, but it does issue the certificate correctly on my domain when unredacted.

**Comment by huang-jy** [comment]
As a test I completely tore down and rebuilt my minikube cluster between tests and both the `dev-nginx` and the sha-based image tag fail, but what I've noticed is that on both images, I do not see the migrations being run, even if I set pixelfed.db.apply_new_migrations_automatically` to true. So potentially does that mean the credentials aren't being set on the DB?

**Comment by jessebot** [comment]
Are you setting the database credentials anywhere? You should have something like this:

```yaml
postgresql:
  auth:
    user: "user"
    postgresPassword: "newPostgresPassword123"
    password: "newUserPassword123"
    replicationPassword: "newReplicationPassword123"
```

Source for the subchart where the above parameters are from:
https://github.com/bitnami/charts/blob/main/bitnami/postgresql/README.md#parameters

> Is there a way to trigger the migrations manually?

I'm not sure actually! I would need to check upstream 🤔 

> Also, there seems to be a discrepancy between the values returned when doing...

That is strange. Can you tell me which version of the chart you have locally? Have you tried `helm repo update`?
